[platformio]
default_envs = lake_node

[env:lake_node]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@^7.1.2
  adafruit/Adafruit ADS1X15@^2.5.0
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.4
lib_extra_dirs = common
build_src_filter =
  +<node/src/>
  -<gateway/src/>
build_flags =
  -std=gnu++17
  -Ifirmware/node/include
