[platformio]
default_envs = lake_node
src_dir = firmware

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@^7.1.2
build_flags =
  -std=gnu++17
build_unflags =
  -std=gnu++11

[env:lake_node]
lib_deps =
  ${env.lib_deps}
  LakeMonitorCommon=symlink://common
  adafruit/Adafruit ADS1X15@^2.5.0
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.4
build_src_filter =
  +<node/src/>
  -<gateway/src/>
  -<diagnostic/src/>
build_flags =
  ${env.build_flags}
  -Ifirmware/node/include

[env:heltec_diagnostic]
build_src_filter =
  +<diagnostic/src/>
  -<node/src/>
  -<gateway/src/>
build_flags =
  ${env.build_flags}
  -Ifirmware/node/include

[env:rak_link_test]
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git#rak
board = wiscore_rak4631
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@^7.1.2
build_src_filter =
  +<rak_link_test/src/>
  -<node/src/>
  -<gateway/src/>
  -<diagnostic/src/>
  -<heltec_link_test/src/>

[env:heltec_link_test]
build_src_filter =
  +<heltec_link_test/src/>
  -<node/src/>
  -<gateway/src/>
  -<diagnostic/src/>
  -<rak_link_test/src/>
build_flags =
  ${env.build_flags}
  -Ifirmware/node/include
